/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhopoo2.guis;

import trabalhopoo2.components.JPanelComImagem;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingConstants;
import javax.swing.WindowConstants;
import trabalhopoo2.components.BtnDefault;
import trabalhopoo2.utils.Utilitarios;

/**
 *
 * @author Iuri
 * @author Dyonathan
 */
public class TelaInicio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicio.class.getName());

    private Font font8Bit;
    private Utilitarios util;
    private final JPanelComImagem panelComImagem;

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        util = new Utilitarios();
        initComponents();
        font8Bit = util.configurarFonte8Bit();
        panelComImagem = new JPanelComImagem(new ImageIcon(getClass().getResource("/resources/imgs/game_image_menu.png")));
        
        configurarJPanelComImagem();
        BtnDefault btn = new BtnDefault(24f, util.COR_FUNDO_BTN, "Jogar", new Dimension(250, 60));

        util.setarFont(lblTitulo, 40f, font8Bit);

        panelComImagem.setLayout(null);
        btn.setBounds(275, 500, 250, 60);
        panelComImagem.add(btn);

        btn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                TelaJogo tj = new TelaJogo();
                tj.setVisible(true);
                dispose();
            }
        }
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new JLabel();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(255, 255, 255));
        setMaximumSize(new Dimension(800, 600));
        setResizable(false);

        lblTitulo.setBackground(new Color(0, 0, 0));
        lblTitulo.setFont(new Font("sansserif", 0, 48)); // NOI18N
        lblTitulo.setForeground(new Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitulo.setText("Corre Cabrito");
        lblTitulo.setInheritsPopupMenu(false);
        lblTitulo.setPreferredSize(new Dimension(500, 100));

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblTitulo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
    private void configurarJPanelComImagem() {
        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(panelComImagem, BorderLayout.CENTER);
        revalidate();
        repaint();
    }
}
