/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhopoo2.guis;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;
import trabalhopoo2.Posicao;
import trabalhopoo2.Tabuleiro;
import trabalhopoo2.exceptions.JogadaInvalidaException;
import trabalhopoo2.model.Carcara;

/**
 *
 * @author lucik
 */
public class TelaJogo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaJogo.class.getName());
    private final Tabuleiro tabuleiro;
    private final List<JLabel> labelsPosicoes = new ArrayList<>();

    /**
     * Creates new form TelaJogo
     */
    public TelaJogo() {
        initComponents();
        tabuleiro = new Tabuleiro();
        labelsPosicoes.addAll(
                List.of(posicao0,
                        posicao1,
                        posicao2,
                        posicao3,
                        posicao4,
                        posicao5)
        );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        posicao0 = new javax.swing.JLabel();
        posicao1 = new javax.swing.JLabel();
        posicao2 = new javax.swing.JLabel();
        posicao3 = new javax.swing.JLabel();
        posicao4 = new javax.swing.JLabel();
        posicao5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        posicao0.setBackground(new java.awt.Color(255, 255, 255));
        posicao0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posicao0.setText("Cabrito");
        posicao0.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        posicao0.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posicao0MouseClicked(evt);
            }
        });

        posicao1.setBackground(new java.awt.Color(255, 255, 255));
        posicao1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posicao1.setText("Carcara");
        posicao1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        posicao1.setPreferredSize(new java.awt.Dimension(2060, 2050));
        posicao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posicao1MouseClicked(evt);
            }
        });

        posicao2.setBackground(new java.awt.Color(255, 255, 255));
        posicao2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posicao2.setText("2");
        posicao2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        posicao2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posicao2MouseClicked(evt);
            }
        });

        posicao3.setBackground(new java.awt.Color(255, 255, 255));
        posicao3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posicao3.setText("3");
        posicao3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        posicao3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posicao3MouseClicked(evt);
            }
        });

        posicao4.setBackground(new java.awt.Color(255, 255, 255));
        posicao4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posicao4.setText("4");
        posicao4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        posicao4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posicao4MouseClicked(evt);
            }
        });

        posicao5.setBackground(new java.awt.Color(255, 255, 255));
        posicao5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        posicao5.setText("5");
        posicao5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        posicao5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posicao5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(posicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(posicao0, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(posicao2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(posicao3, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(248, 248, 248))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(262, 262, 262)
                .addComponent(posicao4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91)
                .addComponent(posicao5, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(posicao0, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicao3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicao2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posicao4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(posicao5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(228, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posicao0MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posicao0MouseClicked
        if (tabuleiro.obterAnimalDaJogada() instanceof Carcara) {
            Posicao posCarcara = tabuleiro.obterPosicaoCarcara();

        } else {

        }
        reposicionarAnimais();
    }//GEN-LAST:event_posicao0MouseClicked

    private void posicao1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posicao1MouseClicked
        throw new JogadaInvalidaException("Erro");
    }//GEN-LAST:event_posicao1MouseClicked

    private void posicao2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posicao2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_posicao2MouseClicked

    private void posicao3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posicao3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_posicao3MouseClicked

    private void posicao4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posicao4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_posicao4MouseClicked

    private void posicao5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posicao5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_posicao5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaJogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel posicao0;
    private javax.swing.JLabel posicao1;
    private javax.swing.JLabel posicao2;
    private javax.swing.JLabel posicao3;
    private javax.swing.JLabel posicao4;
    private javax.swing.JLabel posicao5;
    // End of variables declaration//GEN-END:variables

    public void reposicionarAnimais() {
        posicao0.setText("0");
        posicao1.setText("1");
        posicao2.setText("2");
        posicao3.setText("3");
        posicao4.setText("4");
        posicao5.setText("5");

        int posicaoCarcara = tabuleiro.getPosicoes().indexOf(tabuleiro.obterPosicaoCarcara());
        int posicaoCabrito = tabuleiro.getPosicoes().indexOf(tabuleiro.obterPosicaoCabrito());

        setarTexto(posicaoCarcara, "Carcara");
        setarTexto(posicaoCabrito, "Cabrito");
    }

    private void setarTexto(int posicao, String nomeAnimal) {
        labelsPosicoes.get(posicao).setText(nomeAnimal);
    }
}
