/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package trabalhopoo2.guis;

import trabalhopoo2.components.JPanelComImagem;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.GraphicsEnvironment;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.BorderFactory;
import javax.swing.GroupLayout;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.LayoutStyle;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import trabalhopoo2.utils.Utilitarios;

/**
 *
 * @author Iuri
 * @author Dyonathan
 */
public class TelaInicio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaInicio.class.getName());

    private Font font8Bit;
    private Utilitarios util;

    /**
     * Creates new form TelaInicio
     */
    public TelaInicio() {
        util = new Utilitarios();
        initComponents();
        configurarJPanelComImagem();
        font8Bit = util.configurarFonte8Bit();
        util.configurarBotao(btnJogar);
        util.setarFont(lblTitulo, 40f, font8Bit);
        util.setarFont(btnJogar, 24f, font8Bit);
        UIManager.put("Button.arc", 0);
        UIManager.put("Component.arc", 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new JLabel();
        btnJogar = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(255, 255, 255));
        setMaximumSize(new Dimension(800, 600));
        setResizable(false);

        lblTitulo.setBackground(new Color(0, 0, 0));
        lblTitulo.setFont(new Font("sansserif", 0, 48)); // NOI18N
        lblTitulo.setForeground(new Color(255, 255, 255));
        lblTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        lblTitulo.setText("Corre Cabrito");
        lblTitulo.setInheritsPopupMenu(false);
        lblTitulo.setPreferredSize(new Dimension(500, 100));

        btnJogar.setBackground(new Color(61, 74, 155));
        btnJogar.setForeground(new Color(255, 255, 255));
        btnJogar.setText("JOGAR");
        btnJogar.setBorder(BorderFactory.createLineBorder(new Color(0, 0, 0)));
        btnJogar.setBorderPainted(false);
        btnJogar.setDefaultCapable(false);
        btnJogar.setPreferredSize(new Dimension(74, 23));
        btnJogar.addMouseListener(new MouseAdapter() {
            public void mouseEntered(MouseEvent evt) {
                btnJogarMouseEntered(evt);
            }
            public void mouseExited(MouseEvent evt) {
                btnJogarMouseExited(evt);
            }
        });
        btnJogar.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent evt) {
                btnJogarActionPerformed(evt);
            }
        });

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblTitulo, GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(306, 306, 306)
                .addComponent(btnJogar, GroupLayout.PREFERRED_SIZE, 187, GroupLayout.PREFERRED_SIZE)
                .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblTitulo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 324, Short.MAX_VALUE)
                .addComponent(btnJogar, GroupLayout.PREFERRED_SIZE, 40, GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnJogarActionPerformed(ActionEvent evt) {//GEN-FIRST:event_btnJogarActionPerformed
        TelaJogo tj = new TelaJogo();
        tj.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnJogarActionPerformed

    private void btnJogarMouseEntered(MouseEvent evt) {//GEN-FIRST:event_btnJogarMouseEntered
        btnJogar.setBorder(javax.swing.BorderFactory.createLineBorder(Color.BLACK, 2));
        btnJogar.setForeground(Color.BLACK);
        btnJogar.revalidate();
        btnJogar.repaint();
    }//GEN-LAST:event_btnJogarMouseEntered

    private void btnJogarMouseExited(MouseEvent evt) {//GEN-FIRST:event_btnJogarMouseExited
        btnJogar.setBorder(javax.swing.BorderFactory.createLineBorder(Color.WHITE, 2));
        btnJogar.setForeground(Color.WHITE);
        btnJogar.revalidate();
        btnJogar.repaint();
    }//GEN-LAST:event_btnJogarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicio().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JButton btnJogar;
    private JLabel lblTitulo;
    // End of variables declaration//GEN-END:variables
    private void configurarJPanelComImagem() {
        System.out.println(getClass().getResource("/resources/imgs/game_image_menu.png"));

        JPanelComImagem panelComImagem = new JPanelComImagem(new ImageIcon(getClass().getResource("/resources/imgs/game_image_menu.png")));

        getContentPane().setLayout(new BorderLayout());
        getContentPane().add(panelComImagem, BorderLayout.CENTER);

        revalidate();
        repaint();
    }
}
